apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: argo
spec:
  type: ClusterIP # Only accessible within the cluster
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio