apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-task-result-creator-binding
  namespace: argo # Apply this binding in the 'argo' namespace
subjects:
- kind: ServiceAccount
  name: default # The service account used by the workflow pods
  namespace: argo # Namespace of the service account
roleRef:
  kind: Role
  name: workflow-task-result-creator-role # Name of the Role created above
  apiGroup: rbac.authorization.k8s.io