apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: data-pipeline- # Argo will append a random suffix to the workflow name
spec:
  entrypoint: data-pipeline-dag # The entry template for this workflow
  arguments:
    parameters:
      - name: input-bucket
        value: "raw-data" # Source bucket containing raw input files
      - name: input-key
        value: "ams-data.csv" # Default key (filename) for input; can be overridden at runtime
      - name: processed-bucket
        value: "processed-data" # Bucket to store cleaned/transformed data
      - name: reports-bucket
        value: "reports" # Bucket to store bias reports
      - name: feature-bucket
        value: "feature-store" # Bucket to store split data for model training
      - name: processed-key-suffix
        value: "-processed.parquet" # Suffix to add to the processed data file
      - name: bias-report-key-suffix
        value: "-bias-report.json" # Suffix for the bias report output
      - name: train-key-suffix
        value: "-train.parquet" # Suffix for the training data split
      - name: test-key-suffix
        value: "-test.parquet" # Suffix for the test data split
      - name: val-key-suffix
        value: "-val.parquet" # Suffix for the validation data split
      - name: sensitive-features
        value: "sensitive_attr" # Comma-separated sensitive columns for bias checking
      - name: target-column
        value: "target" # The target column name in the dataset

  templates:

    # ----------------- VALIDATION STEP -----------------
    - name: validate-data
      inputs:
        parameters:
          - name: bucket
          - name: key
      container:
        image: step-validation:latest # Docker image for validation logic
        imagePullPolicy: Never # Ensures local image is used (important for Minikube/local testing)
        command: [python, /app/validate-dummy.py] # Python script to execute
        args: [
          "--bucket", "{{inputs.parameters.bucket}}",
          "--key", "{{inputs.parameters.key}}"
        ]
        env:
          - name: S3_ENDPOINT_URL
            value: "http://minio-service.argo.svc.cluster.local:9000" # S3-compatible MinIO endpoint
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-secrets # Kubernetes secret name
                key: rootUser # Access key ID from secret
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: rootPassword # Secret access key from secret

    # ----------------- PREPROCESSING STEP -----------------
    - name: preprocess-data
      inputs:
        parameters:
          - name: in_bucket
          - name: in_key
          - name: out_bucket
          - name: out_key
      container:
        image: step-preprocess:latest # Image for preprocessing logic
        imagePullPolicy: Never
        command: [python, /app/preprocess-dummy.py]
        args: [
          "--in_bucket", "{{inputs.parameters.in_bucket}}",
          "--in_key", "{{inputs.parameters.in_key}}",
          "--out_bucket", "{{inputs.parameters.out_bucket}}",
          "--out_key", "{{inputs.parameters.out_key}}"
        ]
        env:
          - name: S3_ENDPOINT_URL
            value: "http://minio-service.argo.svc.cluster.local:9000"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: rootUser
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: rootPassword

    # ----------------- BIAS CHECK STEP -----------------
    - name: check-bias
      inputs:
        parameters:
          - name: in_bucket
          - name: in_key
          - name: out_bucket
          - name: report_key
          - name: sensitive_features
          - name: target_col
      container:
        image: step-check-bias:latest # Image containing bias check logic
        imagePullPolicy: Never
        command: [python, /app/check_bias.py]
        args: [
          "--in_bucket", "{{inputs.parameters.in_bucket}}",
          "--in_key", "{{inputs.parameters.in_key}}",
          "--out_bucket", "{{inputs.parameters.out_bucket}}",
          "--report_key", "{{inputs.parameters.report_key}}",
          "--sensitive_features", "{{inputs.parameters.sensitive_features}}",
          "--target_col", "{{inputs.parameters.target_col}}"
        ]
        env:
          - name: S3_ENDPOINT_URL
            value: "http://minio-service.argo.svc.cluster.local:9000"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: rootUser
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: rootPassword

    # ----------------- DATA SPLITTING STEP -----------------
    - name: split-data
      inputs:
        parameters:
          - name: in_bucket
          - name: in_key
          - name: out_bucket
          - name: train_key
          - name: test_key
          - name: val_key
          - name: target_col
      container:
        image: step-split-data:latest # Container image for splitting data into train/test/val
        imagePullPolicy: Never
        command: [python, /app/split_data.py]
        args: [
          "--in_bucket", "{{inputs.parameters.in_bucket}}",
          "--in_key", "{{inputs.parameters.in_key}}",
          "--out_bucket", "{{inputs.parameters.out_bucket}}",
          "--train_key", "{{inputs.parameters.train_key}}",
          "--test_key", "{{inputs.parameters.test_key}}",
          "--val_key", "{{inputs.parameters.val_key}}",
          "--target_col", "{{inputs.parameters.target_col}}"
          # You can add --test_size, --val_size, --random_state if needed
        ]
        env:
          - name: S3_ENDPOINT_URL
            value: "http://minio-service.argo.svc.cluster.local:9000"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: rootUser
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secrets
                key: rootPassword

    # ----------------- PIPELINE DAG DEFINITION -----------------
    - name: data-pipeline-dag
      dag:
        tasks:
          - name: validate
            template: validate-data
            arguments:
              parameters:
              - name: bucket
                value: "{{workflow.parameters.input-bucket}}"
              - name: key
                value: "{{workflow.parameters.input-key}}"

          - name: preprocess
            template: preprocess-data
            dependencies: [validate] # Only runs after 'validate' completes successfully
            arguments:
              parameters:
              - name: in_bucket
                value: "{{workflow.parameters.input-bucket}}"
              - name: in_key
                value: "{{workflow.parameters.input-key}}"
              - name: out_bucket
                value: "{{workflow.parameters.processed-bucket}}"
              - name: out_key
                value: "{{workflow.parameters.input-key}}{{workflow.parameters.processed-key-suffix}}"

          - name: bias-check
            template: check-bias
            dependencies: [preprocess] # Runs after preprocessing is done
            arguments:
              parameters:
              - name: in_bucket
                value: "{{workflow.parameters.processed-bucket}}"
              - name: in_key
                value: "{{workflow.parameters.input-key}}{{workflow.parameters.processed-key-suffix}}"
              - name: out_bucket
                value: "{{workflow.parameters.reports-bucket}}"
              - name: report_key
                value: "{{workflow.parameters.input-key}}{{workflow.parameters.bias-report-key-suffix}}"
              - name: sensitive_features
                value: "{{workflow.parameters.sensitive-features}}"
              - name: target_col
                value: "{{workflow.parameters.target-column}}"

          - name: split
            template: split-data
            dependencies: [bias-check] # Runs after bias analysis completes
            arguments:
              parameters:
              - name: in_bucket
                value: "{{workflow.parameters.processed-bucket}}"
              - name: in_key
                value: "{{workflow.parameters.input-key}}{{workflow.parameters.processed-key-suffix}}"
              - name: out_bucket
                value: "{{workflow.parameters.feature-bucket}}"
              - name: train_key
                value: "{{workflow.parameters.input-key}}{{workflow.parameters.train-key-suffix}}"
              - name: test_key
                value: "{{workflow.parameters.input-key}}{{workflow.parameters.test-key-suffix}}"
              - name: val_key
                value: "{{workflow.parameters.input-key}}{{workflow.parameters.val-key-suffix}}"
              - name: target_col
                value: "{{workflow.parameters.target-column}}"
